### ISSUE TITLE
bgpcpe

### ISSUE THREAD

**Issue by qingqingwuai** [vorburger/opendaylight-simple#101]
It seems that bgpcpe is not yet supported, is that correct?
Are there anyone working on it?

**Comment by tnevrekar** [comment]
@qingqingwuai the main issue in supporting bgpcep is that it uses the OSGi registry internally for dynamic service registration. Unless we rewire that it cannot be included here. BTW this project is being moved to ODL now as ODL-Micro. Backlog here - https://jira.opendaylight.org/projects/ODLMICRO/issues/ODLMICRO-1?filter=allopenissues

**Comment by vorburger** [comment]
@qingqingwuai this project is being moved to ODL, please watch #102 to follow along the progress for that.

I'll be closing all open PRs and Issues here (including this one) when that transition is fully completed.

**Comment by vorburger** [comment]
Closing as per #102.
