### ISSUE TITLE
Transition project to linuxfoundation.org git.opendaylight.org odlmicro.git, and archive this project on GitHub

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-simple#102]
The goal of this issue is to transition this project (https://github.com/vorburger/opendaylight-simple/) to the linuxfoundation.org hosted https://git.opendaylight.org into the odlmicro.git repository at https://git.opendaylight.org/gerrit/gitweb?p=odlmicro.git;a=tree.

I would very very much like the commit history of this project to survive that transition if there is any way at all that is possible.

Once this is completely done, I'll update the README and archive this project to make it read-only on GitHub.

**Comment by vorburger** [comment]
The Linux Foundation requires all commits to have the `Signed-off-by: Michael Vorburger <mike@vorburger.ch>`, which (most) of my commits in this repo didn't have. I'll try to figure out how to somehow add those and push that to a new branch here...

> Once this is completely done, I'll update the README and archive this project to make it read-only on GitHub.

I'll also be closing all open PRs (#79 and #92) and Issues in this project here, once the transition is fully completed. https://jira.opendaylight.org/projects/ODLMICRO/issues/ODLMICRO-1?filter=allopenissues is where new issues can be created.

@tnevrekar FYI you may want to Subscribe to and watch this issue? :smile: I'll also let you transition (i.e. copy/paste) any of [the 11 open issues](https://github.com/vorburger/opendaylight-simple/issues) to the ODL JIRA before I close them, if you find any of them useful or interesting. I noticed that you have already opened some issues there from [the project's TODO.md](https://github.com/vorburger/opendaylight-simple/blob/master/TODO.md).

**Comment by vorburger** [comment]
> requires all commits to have Signed-off-by:

Done on https://github.com/vorburger/opendaylight-simple/tree/issue-102_Signed-off-by

It’s pretty much exactly the original as on the current `master` branch, except that I have removed @tnevrekar PR #100 as it had no sign-off (it's probably easiest to just re-add this via Gerrit on ODL), and removed @shague bfef768cbabfc6cfad817bf459b5d808622358aa which had no sign-off (but that particular commit can easily just be dropped - it’s not required to migrate).

**Comment by tnevrekar** [comment]
Thanks Michael. I am happy to add my commit once imported into ODL.

**Comment by tnevrekar** [comment]
I have added tasks a EPIC here -
https://jira.opendaylight.org/browse/ODLMICRO-1 as you said from the TODO.
I looked through all the issues in github and added relevant onces in the
same epic upstream. pls let me know if anything is missing. thanks.

**Comment by vorburger** [comment]
The _issue-102_Signed-off-by_ branch was imported into [the odl-micro repository](https://git.opendaylight.org/gerrit/gitweb?p=odlmicro.git;a=shortlog) yesterday.

I've updated the README remaining in this project here in ad6f699daa4b71cd075699cc1e952f7430465988 to clarify the move. (And I've also "removed" code on the default branch in a previous commit; nota bene that the full original code with history is obviously still in git, and I've made it visible and easily Web browseable on an [ARCHIVE branch](https://github.com/vorburger/opendaylight-simple/commits/ARCHIVE) on this repository.

BTW this project originally used a branch named `master`, but I have now made a new branch named `develop` to be this repository's default branch, and deleted `master`, because **_#BlackLivesMatter_** - see background about this e.g. on [ZDNet](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) or [BBC](https://www.bbc.com/news/technology-53050955) or [this tweet](https://twitter.com/natfriedman/status/1271253144442253312).

I'll soon close all other open issues and my 2 old PRs #79 and #92 and then Archive this project.

**Comment by vorburger** [comment]
I'm considering this fully completed now, and am closing remaining open PRs and issues, and Archiving this project on GitHub.

**Comment by vorburger** [comment]
http://blog2.vorburger.ch/2020/07/transitioning-opendaylight-simple-to.html
