### ISSUE TITLE
Add zip of tarball

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#28]
The tarball is now being uploaded and downloaded so it would be best to compress as best as possible. The current tarball is just the jars, so if that is already compressed then no need to add the zip now.

**Comment by vorburger** [comment]
> The current tarball is just the jars, so if that is already compressed then no need to add the zip now.

yep exactly, I had found that it actually makes little difference - but the build is slower with compression / very fast now. I would therefore like to keep it as a simple tar, if that is OK for you - close this issue?

@skitt FYI
