### ISSUE TITLE
Add diagstatus ready message to log

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#29]
The deploy and run scripts look for diagstatus in the log to know when the controller is up and ready, i.e. grep 'org.opendaylight.infrautils.*System ready' /tmp/${BUNDLEFOLDER}/data/log/karaf.log. I see the new log is opendaylight.log, so it just needs to include the disgstatus or equivalent ready log.

**Comment by vorburger** [comment]
It's not about "just the log", but having infrautils.ready & diagstatus work in simple...

[ReadyWiring](https://github.com/vorburger/opendaylight-simple/blob/master/src/main/java/org/opendaylight/infrautils/simple/ReadyWiring.java) has a start, I need to have a closer look what is missing... 

#19 is probably needed and will (at least partially) help here.

Let's keep this issue open to also include and only close when `GET /diagstatus` also works.

**Comment by shague** [comment]
Sounds  good. This is a high-priority one since the tests can't really move forward without knowing the controller is up and ready. Noted in the other issue with getSvcstatus we need the disagstatus wired there also.

**Comment by vorburger** [comment]
> This is a high-priority one

ACK

> getSvcstatus we need the disagstatus wired there also

happy to say that having a working `showSvcStatus` is part of ("in scope") of this issue!

**Comment by vorburger** [comment]
> a working showSvcStatus

#39

**Comment by vorburger** [comment]
>  when GET /diagstatus also works

#41

**Comment by tnevrekar** [comment]
Not adding this ODL Upstream as most of it is merged already.
