### ISSUE TITLE
Method to modify the opendaylight.log levels and loggers

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#31]

**Comment by vorburger** [comment]
yup, this is ultimately needed. Certainly not the first thing I plan on jumping, got bigger fish to fry, first.

Any contributions always around this welcome, of course. @skitt FYI.

**Comment by vorburger** [comment]
This issue could perhaps dynamic logger reconfiguration via `log:log`, if we truly need that.

**Comment by tnevrekar** [comment]
Added here - https://jira.opendaylight.org/browse/ODLMICRO-22
