### ISSUE TITLE
cli equivalent in the odl-simple distro

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#33]
What is the equivalent cli in the simple world?

The tests themselves will need to be reworked here also since the test lib is doing karaf keyword calls. This will end up as a very large change to the CSIT as the CSIT uses karaf keywords in many places.

Some examples of what csit expects from cli:

- feature:install
- showSvcStatus
- log:log

**Comment by vorburger** [comment]
How about instead of having a "generic" issue like this we have more specific issues for everything missing?

> feature:install

#30

> showSvcStatus

#29

> log:log

#31

Close this issue?

**Comment by shague** [comment]
Sure, will add specific cli's as unique issues. I would still like an intro on the new cli and how to call that from an ssh shell to ODL. All the cli's would need to use that flow. So maybe add that here and then close?

**Comment by vorburger** [comment]
>> how to call that from an ssh shell to ODL
> that actually is currently a gap which would definitely be worth it's own new issue, yes!

#36 

@shague I don't think there is anything left here now, so close this issue?

**Comment by tnevrekar** [comment]
Not moving this ODL upstream as nothing specific needed here
