### ISSUE TITLE
Implement a server or daemon mode

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#34]
The current mode dumps everything to the console so it is very noisy. it would be good to daemon mode that runs in the background and logs everything.

**Comment by vorburger** [comment]
I'm not sure that I would agree that a real "daemon" is needed... just discussed this with @skitt and I now think if we had the CLI available via ssh (which we will do in #36 !), and perhaps then later had a mode where the CLI would only be by SSH and no longer in the foreground (the equivalent of Karaf's `bin/karaf server`, basically our `-Dkaraf.startLocalConsole=false -Dkaraf.startRemoteShell=true` but implemented not with via Java system properties but both as a optional features selected at boot time), then we would perhaps already be "done" with this requirement here. 

So let's keep this issue open until after #36 and then conclude it.

**Comment by shague** [comment]
Yes, that is the real request - to have the same look and feel we have karaf console today since that is what most expect and the CSIT uses. Early on with CSIT when the karaf console was used in the wrong mode, it would randomly exit. It was ctrl-d somehow being issued in some way and the console would exit.

**Comment by tnevrekar** [comment]
Addeed https://jira.opendaylight.org/browse/ODLMICRO-21
