### ISSUE TITLE
Automatic continous deployment

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-simple#42]
We would like this project to be automatically built and deployed somewhere so tests can run against it.

**Comment by vorburger** [comment]
@shague made a start for this in #26 based on https://docs.travis-ci.com/user/deployment/releases/ - I've [done similar things in the past](https://github.com/m2e-code-quality/m2e-code-quality/issues/123) based on https://docs.travis-ci.com/user/deployment/pages/ and prefer that because we don't want to have to "manually release" by tagging - we need true CI/CD here.

Unfortunately there is a snag - our "distro" is too big; see https://github.com/travis-ci/travis-ci/issues/10211.

**Comment by vorburger** [comment]
Required clean-up when this is concluded:

1. remove https://github.com/vorburger/opendaylight-simple-binaries/settings
2. remove Personal Access Token on https://github.com/settings/tokens
3. remove GITHUB_TOKEN from https://travis-ci.org/vorburger/opendaylight-simple/settings
4. remove `deploy:` section from `.travis.yml`

**Comment by vorburger** [comment]
@shague could we not simply have a build on https://jenkins.opendaylight.org instead?

**Comment by vorburger** [comment]
> Unfortunately there is a snag - our "distro" is too big

This affects gh-pages but not releases deploy; see https://github.com/shague/opendaylight-simple/releases ... I cannot download those, gets stuck about 3/4 through, always, reproducible, but that must be my ISP (I've had problems before).

I've therefore gone back from pages to releases in 12f660cb821755845701f50cc73f990cf2fdd414.

> @shague could we not simply have a build on https://jenkins.opendaylight.org instead?

I've meanwhile learnt (from Anil Belur) that this would be possible on the sandbox, through contributions to job templates in ODL's `integration/builder` project, but that a sandbox job could not deploy to `nexus.opendaylight.org`. So the CSIT would have to pull from the archived Jenkins output (kept for 1 week) ... let's forget that.

> 1. remove https://github.com/vorburger/opendaylight-simple-binaries/settings

done 

> 2. remove Personal Access Token on https://github.com/settings/tokens

done

> remove GITHUB_TOKEN from https://travis-ci.org/vorburger/opendaylight-simple/settings

done

> remove deploy: section from .travis.yml

done in 12f660cb821755845701f50cc73f990cf2fdd414

> revert (probably) 4aa336d

done in 5e2540f648bb673341d21c2874353913d98e8ee8

Now I'm just waiting for a very slow (due to #37) first build with this to finish...

**Comment by vorburger** [comment]
Seems to work - see https://github.com/vorburger/opendaylight-simple/releases

The list will quickly fill up; I'll have to either manually remove ...

... or find a find to overwrite a single same _LATEST_ one?

@shague is this what we wanted? Won't the CSIT script struggle to `wget` it, with names changing?

**Comment by shague** [comment]
Yes, this random string is an issue since the CSIT will not know it. some options:

1. The csit does a query on the releases page and grabs the latest
2. add TRAVIS_TAG in the .travis.yml and go back to only building on tags. You would have a check like if -n $TRAVIS_TAG then TRAVIS_TAG="0.1.0-SNAPSHOP"
That would deploy if a tag is set or if not, then we will always set a tag to the 0.1.0-SNAPSHOT and push that - it would overwrite the current one. That way we always have a 0.1.0-SNAPSHOT for CSIT to grab. 

Also the csit takes a url also to download. So we can always put the untageed random string in there, or change to the latest version.

**Comment by tnevrekar** [comment]
Not relevant to the ODL upstreaming as it has its own way of CSIT.

**Comment by vorburger** [comment]
Closing as per #102.
