### ISSUE TITLE
CLI log:log

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-simple#46]
The CSIT tests extensively use `log:log` to write what they are doing.

We should support this as well.

**Comment by vorburger** [comment]
@skitt should I just add a simple `Action` for this, or do you want to use Karaf's own "real thing" here too?

**Comment by skitt** [comment]
> @skitt should I just add a simple `Action` for this, or do you want to use Karaf's own "real thing" here too?

You can add an `Action` now if you want, and I’ll remove it when I pull in Karaf’s log commands.

**Comment by tnevrekar** [comment]
Moved this to https://jira.opendaylight.org/browse/ODLMICRO-19

**Comment by vorburger** [comment]
Closing as per #102.
