### ISSUE TITLE
Get ovsdb wired up correctly and test it in CSIT

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-simple#47]
we need to have a go at reading ovsdb BP XML and writing some *Wiring ...

perhaps we could convert ovsdb to use @Singleton and @Inject and use our Scanner

**Comment by vorburger** [comment]
@shague or @skitt said in today's genius weekly meeting that they may jump at this some time.

**Comment by tnevrekar** [comment]
@vorburger AFAIK this is already completed upstream - https://git.opendaylight.org/gerrit/c/ovsdb/+/79782

**Comment by vorburger** [comment]
Closing as per #102.
